### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by Krappa420** [valerypatorius/zenbiuu#12]
Unable to login, says browser not supported. Please see screenshot

![image](https://user-images.githubusercontent.com/66475753/231873955-1ac18b8c-0eff-4bdf-ba4f-cb7a1712a55e.png)

**Comment by valerypatorius** [comment]
Wow, that's something new. Does not seem to be caused by User-Agent. I will investigate and report back

**Comment by valerypatorius** [comment]
Ended up updating authorization flow completely. It is now being handled through the default browser. 
Could not find any useful info about browsers restrictions, only similar reports from Brave browser users dated September 2022 🤷 

Cons:
- One extra action from user in order to return back to the app

Pros:
- If you have logged into Twitch account in the browser earlier, you won't have to input account data again in the app
